language: python
# lets try them all :D
python:
  - "2.5"
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"
install:
  - "python setup.py develop"
script:
  - "python setup.py test"
notifications:
  - "irc.sioff.net#kiberpipa"
